repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: tests/charts/demo/templates/.*.yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        # args:
        #   # Make the tool search for charts only under the `charts` directory
        #   - --chart-search-root=charts

  - repo: https://github.com/losisin/helm-values-schema-json
    rev: v1.6.4
    hooks:
      - id: helm-schema
        args:
          - "-indent"
          - "2"
          - "-input"
          - "charts/paperless-ngx/values.yaml"
          - "--output"
          - "charts/paperless-ngx/values.schema.json"
      - id: helm-schema
        args:
          - "-indent"
          - "2"
          - "-input"
          - "charts/gotenberg/values.yaml"
          - "--output"
          - "charts/gotenberg/values.schema.json"
