{{- if and (eq .Values.certificates.exsistingSecretName "") ( not .Values.certificates.certmanager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-admission.fullname" . }}-cert
  labels:
    app: {{ template "k8s-admission.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ca.crt: {{ index .Values.certificates "ca.crt" }}
  tls.crt: {{ index .Values.certificates "tls.crt" }}
  tls.key: {{ index .Values.certificates "tls.key" }}


{{- end }}
