apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-admission.fullname" . }}
  labels:
    {{- include "k8s-admission.labels" . | nindent 4 }}
  annotations:
    {{- include "k8s-admission.service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-admission.selectorLabels" . | nindent 4 }}
