{{- if .Values.validatingWebhooks.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "k8s-admission.fullname" . }}
  annotations:
    deployment: "{{ .Release.Namespace }}/{{ include "k8s-admission.fullname" . }}"
    {{- if .Values.certificates.certmanager.enabled }}
    # Docs: https://cert-manager.io/v1.5-docs/concepts/ca-injector/
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "k8s-admission.fullname" . }}"
    {{- else }}
    {{- if eq .Values.certificates.exsistingSecretName ""}}
    cert-manager.io/inject-ca-from-secret: "{{ .Release.Namespace }}/{{ include "k8s-admission.fullname" . }}-cert"
    {{- else }}
    cert-manager.io/inject-ca-from-secret: "{{ .Release.Namespace }}/{{ .Values.certificates.exsistingSecretName }}"
    {{- end }}
    {{- end }}
webhooks:
{{- if .Values.validatingWebhooks.allowdImages.enabled }}
- name: allowed-images.hegerdes.com
  admissionReviewVersions: [v1]
  {{- if not .Values.certificates.certmanager.enabled }}
  clientConfig:
    caBundle: {{ index .Values.certificates "ca.crt" }}
  {{- end }}
  {{- with .Values.validatingWebhooks.allowdImages.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  clientConfig:
    service:
      name: {{ include "k8s-admission.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /allowed-images
      port: {{ .Values.service.port }}
  rules:
  - apiGroups: [""]
    apiVersions: [v1]
    operations: [CREATE, UPDATE]
    resources: [pods]
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
{{- end }}
{{- if .Values.validatingWebhooks.allowWithDelay.enabled }}
- name: always-allow-delay-5s.hegerdes.com
  admissionReviewVersions: [v1]
  {{- if not .Values.certificates.certmanager.enabled }}
  clientConfig:
    caBundle: {{ index .Values.certificates "ca.crt" }}
  {{- end }}
  {{- with .Values.validatingWebhooks.allowWithDelay.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  clientConfig:
    service:
      name: {{ include "k8s-admission.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /always-allow-delay-5s
      port: {{ .Values.service.port }}
  rules:
  - apiGroups: [""]
    apiVersions: [v1]
    operations: [CREATE, UPDATE]
    resources: [pods]
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
{{- end }}
{{- end }}
