FROM rust:1-trixie AS build

# Install dev deps
RUN sed -i 's|^Components: main$|Components :main non-free non-free-firmware|' /etc/apt/sources.list.d/debian.sources
RUN apt-get update -qq && apt-get install -y -qq \
    cmake musl-tools clang llvm libclang-dev \
    make curl git gcc build-essential pkgconf m4 libtool libsystemd-dev \
    libprotobuf-c-dev libcap-dev libseccomp-dev libyajl-dev libyajl2 \
    libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libgcrypt20-dev \
    python3-protobuf go-md2man libtool autoconf python3 automake bison \
    golang-github-checkpoint-restore-go-criu-dev libcudart12 libcriu-dev \
    jq gawk gperf flex libjson-c-dev libprotobuf-c-dev

# Add in later debian version
# libblake3-dev

# Build Args
ARG WasmEdgeApiVersion=0.1.1
ARG LibKrunVersion=main
ARG CrunVersion=main

# Install wasmedge
# See https://wasmedge.org/book/en/quick_start/install.html
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s --

WORKDIR /builder
RUN git clone --branch ${CrunVersion} --depth 20 https://github.com/containers/crun.git
RUN git clone --branch ${LibKrunVersion} --depth 20 https://github.com/containers/libkrun.git

RUN --mount=type=cache,target=/builder/libkrun/target/ cd libkrun && make && make install
RUN source $HOME/.wasmedge/env \
    && cd crun \
    && ./autogen.sh \
    && ./configure --with-wasmedge --with-libkrun --enable-embedded-blake3 \
    && make -j $(nproc) \
    && mkdir -p wasmlibs \
    && mkdir -p krunlibs \
    && cp -v /usr/local/lib64/libkrun.so* krunlibs/ \
    && cp $HOME/.wasmedge/lib/libwasmedge.so* wasmlibs/ \
    && tar czvf "crun-$(git rev-parse --short HEAD)_$(uname -m).tar.gz" \
     --exclude='*.so' --exclude='krunlibs/*.so.1' --exclude='wasmlibs/*.so.0' \
    crun COPYING NEWS README.md wasmlibs krunlibs \
    && if [ "$(uname -m)" = "x86_64" ]; then ./crun --version; fi

RUN cp crun/crun*.tar.gz .

# FROM rust:1-trixie AS final
# WORKDIR /builder
# COPY --from=build /builder/crun-*.tar.gz /builder
