name: Test reusables

on:
  push:
    branches: [main]
    paths:
      - ".github/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/**"

permissions:
  contents: read
  id-token: write

jobs:
  reusable-test-docker:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      build-name: ghcr.io/${{ github.repository_owner }}/helper-suite
      build-tags: latest
      build-labels: MAINTAINER=${{ github.repository_owner }}
      push: false
      build-dockerfile: tests/Dockerfile
      build-platforms: linux/amd64,linux/arm64
      extra-commands: echo "Your commands here"

  reusable-test-helm:
    uses: ./.github/workflows/reusable-helm-package.yml
    with:
      chart-sources-dir: tests/charts
      chart-publish: false
      chart-release-version: "0.1.0"
      extra-commands: echo "Your commands here"
