name: Docker-Build-Scan-and-Sign

on:
  workflow_call:
    inputs:
      build-repo:
        description: "The repo to clone and build"
        default: ${{ github.repository }}
        type: string
        required: false
      build-context:
        description: "The build context path"
        default: "."
        type: string
        required: false
      build-dockerfile:
        description: "The build path to the Dockerfile, relative to the context"
        default: Dockerfile
        type: string
        required: false
      build-name:
        description: "The base name for the Docker-Image"
        type: string
        required: true
      build-tags:
        description: "The tags for the Docker-Image. Needs to be newline seperated."
        type: string
        required: true
      build-args:
        description: "Args passed to the build-process"
        type: string
        default: ""
        required: false
      build-labels:
        description: "Labels set to the build"
        default: ""
        type: string
        required: false
      build-cache:
        description: "The cache location for the build"
        default: ""
        type: string
        required: false
      build-platforms:
        description: "The platforms to build the image for"
        default: "linux/amd64"
        type: string
        required: false
      push:
        description: "If images shoud be pushed"
        type: boolean
        default: true
        required: false
      oci-registry:
        description: "The tags for the Docker-Image"
        default: ""
        type: string
        required: false
      extra-envs:
        description: "Extra envs passed to the runner. Format: VAR1=VAL1;VAR2=VAL2..."
        default: ""
        type: string
        required: false
      extra-commands:
        description: "Extra commands run in the workflow"
        default: ""
        type: string
        required: false
      scan-image:
        description: "If image should be scaned for vulnerabilities"
        default: true
        type: boolean
        required: false
      scan-image-severity:
        description: "Severities of vulnerabilities to scanned for and displayed. Supports UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
        default: HIGH,CRITICAL
        type: string
        required: false
      scan-image-trivy-config:
        description: "Path to trivy-config"
        default: ""
        type: string
        required: false
      scan-image-trivy-exit-code:
        description: "Exit code of trivy"
        default: 0
        type: number
        required: false
      scan-checkov-args:
        description: "Extra args for checkov"
        default: "--soft-fail"
        type: string
        required: false
      runner:
        description: "The GH-Runner to use"
        default: "ubuntu-latest"
        type: string
        required: false
      environment:
        description: "GitHub Environment"
        default: "default"
        type: string
        required: false
    secrets:
      AZURE_CLIENT_ID:
        description: "Azure OAuth2 ClientId"
        required: false
      AZURE_TENANT_ID:
        description: "Azure AD Tenant"
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: "Azure SubscriptionId"
        required: false
      REGISTRY_USER:
        description: "Container Registry User"
        required: false
      REGISTRY_PW:
        description: "Container Registry PW/Token"
        required: false
      COSIGN_KEY_OR_KMS:
        description: "The cosign pvt or the KMS URL"
        required: false
      MASK_ENVS:
        description: "Extra envs passed to the runner. Format: VAR1=VAL1;VAR2=VAL2..."
        required: false
    outputs:
      docker-digest:
        description: "The Docker Image DIGEST sha"
        value: ${{ jobs.build-image.outputs.DOCKER_DIGEST }}
      sign-signatures:
        description: "The Cosign signatures. Seperated by ',' when there is more then one"
        value: ${{ jobs.sign-image.outputs.SIGN_SIGNATURES }}

jobs:
  build-image:
    outputs:
      COSIGN_RUN: ${{ steps.env-setup.outputs.COSIGN_KEY_SET }}
      DOCKER_DIGEST: ${{ steps.build-and-push.outputs.digest }}
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.build-repo }}

      - name: Set ENVs
        id: env-setup
        run: |
          export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAMES%%,*}"
          export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAGS%%,*}"
          echo "DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          for MY_VAR in $(echo "${{ inputs.extra-envs }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          for MY_VAR in $(echo "${{ secrets.MASK_ENVS }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          if [ "$AZURE_CLIENT_ID" != "" ]; then
            echo "AZ_LOGIN_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$COSIGN_KEY_OR_KMS" != "" ]; then
            echo "COSIGN_KEY_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$REGISTRY_PW" != "" ]; then
            echo "REGISTRY_PW_SET=yes" >> "$GITHUB_OUTPUT"
          fi
        env:
          COSIGN_KEY_OR_KMS: ${{ secrets.COSIGN_KEY_OR_KMS }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
          DOCKER_IMAGE_NAMES: ${{ inputs.build-name }}
          DOCKER_IMAGE_TAGS: ${{ inputs.build-tags }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ inputs.oci-registry }}
        uses: docker/login-action@v3
        if: inputs.push && steps.env-setup.outputs.REGISTRY_PW_SET == 'yes'
        with:
          registry: ${{ inputs.oci-registry }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Log into registry GitHub
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in with Azure
        if: steps.env-setup.outputs.AZ_LOGIN_SET == 'yes'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.build-name }}
          tags: ${{ inputs.build-tags }}
          labels: ${{ inputs.build-labels }}

      - name: Run passed commands
        run: bash -c "${{ inputs.extra-commands }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          sbom: true
          provenance: true
          load: ${{ !inputs.push }}
          push: ${{ inputs.push }}
          tags: ${{ steps.metadata.outputs.tags }}
          file: ${{ inputs.build-dockerfile }}
          cache-to: ${{ inputs.build-cache }}
          cache-from: ${{ inputs.build-cache }}
          context: ${{ inputs.build-context }}
          platforms: ${{ inputs.build-platforms }}
          build-args: ${{ inputs.build-args }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Azure Logout
        if: (success() || failure()) && steps.env-setup.outputs.AZ_LOGIN_SET == 'yes'
        continue-on-error: true
        run: |
            az logout
            az cache purge
            az account clear

  scan-image:
    runs-on: ${{ inputs.runner }}
    if: inputs.scan-image
    needs: build-image
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.build-repo }}

      - name: Set ENVs
        id: env-setup
        run: |
          export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAMES%%,*}"
          export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAGS%%,*}"
          echo "DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          for MY_VAR in $(echo "${{ inputs.extra-envs }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          for MY_VAR in $(echo "${{ secrets.MASK_ENVS }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          if [ "$AZURE_CLIENT_ID" != "" ]; then
            echo "AZ_LOGIN_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$COSIGN_KEY_OR_KMS" != "" ]; then
            echo "COSIGN_KEY_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$REGISTRY_PW" != "" ]; then
            echo "REGISTRY_PW_SET=yes" >> "$GITHUB_OUTPUT"
          fi
        env:
          COSIGN_KEY_OR_KMS: ${{ secrets.COSIGN_KEY_OR_KMS }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
          DOCKER_IMAGE_NAMES: ${{ inputs.build-name }}
          DOCKER_IMAGE_TAGS: ${{ inputs.build-tags }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run checkov
        id: checkov_run
        run: |
          pip3 install checkov
          checkov --file ${{ inputs.build-dockerfile }} ${{ inputs.scan-checkov-args }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ steps.env-setup.outputs.DOCKER_IMAGE }}
          hide-progress: false
          format: sarif
          output: trivy-results.sarif
          exit-code: ${{ inputs.scan-image-trivy-exit-code }}
          trivy-config: ${{ inputs.scan-image-trivy-config }}
          severity: ${{ inputs.scan-image-severity }}

      - name: Upload Trivy scan results to GitHub Security tab
        if: (success() || failure())
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'

  sign-image:
    runs-on: ${{ inputs.runner }}
    outputs:
      SIGN_SIGNATURES: ${{ steps.sign.outputs.SIGN_SIGNATURES }}
    if: needs.build-image.outputs.COSIGN_RUN == 'yes'
    needs: build-image
    environment: ${{ inputs.environment }}
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Set ENVs
        id: env-setup
        run: |
          export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAMES%%,*}"
          export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAGS%%,*}"
          echo "DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          for MY_VAR in $(echo "${{ inputs.extra-envs }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          for MY_VAR in $(echo "${{ secrets.MASK_ENVS }}" | tr ";" "\n"); do
            echo "$MY_VAR" >> $GITHUB_ENV
            echo "$MY_VAR" >> $GITHUB_OUTPUT
          done
          if [ "$AZURE_CLIENT_ID" != "" ]; then
            echo "AZ_LOGIN_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$COSIGN_KEY_OR_KMS" != "" ]; then
            echo "COSIGN_KEY_SET=yes" >> "$GITHUB_OUTPUT"
          fi
          if [ "$REGISTRY_PW" != "" ]; then
            echo "REGISTRY_PW_SET=yes" >> "$GITHUB_OUTPUT"
          fi
        env:
          COSIGN_KEY_OR_KMS: ${{ secrets.COSIGN_KEY_OR_KMS }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
          DOCKER_IMAGE_NAMES: ${{ inputs.build-name }}
          DOCKER_IMAGE_TAGS: ${{ inputs.build-tags }}

      - name: Log into registry ${{ inputs.oci-registry }}
        uses: docker/login-action@v3
        if: inputs.push && steps.env-setup.outputs.REGISTRY_PW_SET == 'yes'
        with:
          registry: ${{ inputs.oci-registry }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Log into registry GitHub
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in with Azure
        if: steps.env-setup.outputs.AZ_LOGIN_SET == 'yes'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run passed commands
        run: bash -c "${{ inputs.extra-commands }}"

      - name: Sign Docker image
        id: sign
        run: |
          if [[ "$COSIGN_KEY" != *"kms"* ]] && [[ "$COSIGN_KEY" != *"k8s"* ]] && [[ "$COSIGN_KEY" != *"hashivault"* ]]; then
            echo "No KMS setup found. Using local key setup. Make sure the cosign decryption env is set."
            echo "$COSIGN_KEY" > cosign.key
            COSIGN_KEY=cosign.key
          else
            echo "Using KMS setup. Make sure the access to the KSM is set."
          fi
          if [ "${{ inputs.push }}" == "false" ]; then
            echo "Cosign upload disabled."
            COSIGN_UPLOAD_ARGS="--upload=false"
          fi
          for MY_IMG_NAME in $(echo "${{ inputs.build-name }}" | tr "," "\n"); do
            MY_IMG_SIG_NAME=$(echo $MY_IMG_NAME | tr '/' '-')
            echo "Signing ${MY_IMG_NAME}@${{ needs.build-image.outputs.DOCKER_DIGEST }}..."
            echo "Running: cosign sign --key $COSIGN_KEY $COSIGN_UPLOAD_ARGS $COSIGN_EXTRA_ARGS \
              --yes --recursive \
              --output-signature sig-${MY_IMG_SIG_NAME} \
              -a build-by=$GITHUB_ACTOR \
              -a repo=$GITHUB_REPOSITORY \
              -a repo-sha=$GITHUB_SHA \
              ${MY_IMG_NAME}@${{ needs.build-image.outputs.DOCKER_DIGEST }}"
            cosign sign --key $COSIGN_KEY $COSIGN_UPLOAD_ARGS $COSIGN_EXTRA_ARGS \
              --yes --recursive \
              --output-signature sig-${MY_IMG_SIG_NAME} \
              -a build-by=$GITHUB_ACTOR \
              -a repo=$GITHUB_REPOSITORY \
              -a repo-sha=$GITHUB_SHA \
              ${MY_IMG_NAME}@${{ needs.build-image.outputs.DOCKER_DIGEST }}
          done
          ls -l sig-*
          echo "SIGN_SIGNATURES=$(cat sig-*)"
          echo "SIGN_SIGNATURES=$(cat sig-*)" >> "$GITHUB_OUTPUT"
          rm -rf cosign.key
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY_OR_KMS }}
          AZURE_AUTH_METHOD: cli

      - name: Azure Logout
        if: (success() || failure()) && steps.env-setup.outputs.AZ_LOGIN_SET == 'yes'
        continue-on-error: true
        run: |
            az logout
            az cache purge
            az account clear
