name: Comunity-Tasks-Issue/PR

on:
  workflow_call:
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          issue-message: "Hi, thank for reporting an issue, we will check it out very soon"
          pr-message: "Hi, thank you for contributing, we will check it out very soon"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
